
/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
import { FurnitureConfig, FurnitureType } from './types';

export const GRID_SIZE = 12;
export const TICK_RATE_MS = 3000;
export const INITIAL_BUDGET = 5000; // Tăng ngân sách khởi đầu một chút vì có nhiều đồ hơn

export const FURNITURE: Record<FurnitureType, FurnitureConfig> = {
  [FurnitureType.None]: {
    type: FurnitureType.None,
    cost: 0,
    name: 'Xóa',
    description: 'Xóa vật phẩm.',
    color: '#ef4444',
    styleGen: 0,
    comfortGen: 0,
  },
  [FurnitureType.Flooring]: {
    type: FurnitureType.Flooring,
    cost: 50,
    name: 'Thảm',
    description: 'Chất liệu mềm mại.',
    color: '#d4a373',
    styleGen: 5,
    comfortGen: 2,
  },
  [FurnitureType.Seating]: {
    type: FurnitureType.Seating,
    cost: 400,
    name: 'Sofa',
    description: 'Thoải mái hiện đại.',
    color: '#7f5539',
    styleGen: 15,
    comfortGen: 25,
  },
  [FurnitureType.Table]: {
    type: FurnitureType.Table,
    cost: 200,
    name: 'Bàn nhỏ',
    description: 'Bàn cà phê.',
    color: '#9c6644',
    styleGen: 8,
    comfortGen: 5,
  },
  [FurnitureType.LargeTable]: {
    type: FurnitureType.LargeTable,
    cost: 450,
    name: 'Bàn ăn',
    description: 'Bàn lớn cho gia đình.',
    color: '#8b5a2b',
    styleGen: 12,
    comfortGen: 10,
  },
  [FurnitureType.Bed]: {
    type: FurnitureType.Bed,
    cost: 800,
    name: 'Giường',
    description: 'Giấc ngủ sang trọng.',
    color: '#b7b7a4',
    styleGen: 20,
    comfortGen: 50,
  },
  [FurnitureType.Storage]: {
    type: FurnitureType.Storage,
    cost: 300,
    name: 'Tủ',
    description: 'Đơn vị lưu trữ.',
    color: '#6b705c',
    styleGen: 10,
    comfortGen: 0,
  },
  [FurnitureType.Bookshelf]: {
    type: FurnitureType.Bookshelf,
    cost: 550,
    name: 'Kệ sách',
    description: 'Kệ sách cao.',
    color: '#3d405b',
    styleGen: 25,
    comfortGen: 5,
  },
  [FurnitureType.Electronics]: {
    type: FurnitureType.Electronics,
    cost: 1200,
    name: 'TV',
    description: 'Hệ thống giải trí.',
    color: '#2d2d2d',
    styleGen: 40,
    comfortGen: 15,
  },
  [FurnitureType.Decor]: {
    type: FurnitureType.Decor,
    cost: 150,
    name: 'Cây xanh',
    description: 'Nét xanh tươi.',
    color: '#588157',
    styleGen: 30,
    comfortGen: 0,
  },
  [FurnitureType.Wall]: {
    type: FurnitureType.Wall,
    cost: 100,
    name: 'Tường',
    description: 'Phân chia không gian.',
    color: '#e5e5e5',
    styleGen: 2,
    comfortGen: 0,
  },
  [FurnitureType.Window]: {
    type: FurnitureType.Window,
    cost: 350,
    name: 'Cửa sổ',
    description: 'Ánh sáng tự nhiên.',
    color: '#a2d2ff',
    styleGen: 20,
    comfortGen: 5,
  },
  [FurnitureType.Door]: {
    type: FurnitureType.Door,
    cost: 400,
    name: 'Cửa',
    description: 'Lối vào.',
    color: '#5e3023',
    styleGen: 10,
    comfortGen: 0,
  },
  [FurnitureType.Chair]: {
    type: FurnitureType.Chair,
    cost: 150,
    name: 'Ghế',
    description: 'Ghế 4 chân tiện dụng.',
    color: '#a0522d',
    styleGen: 8,
    comfortGen: 15,
  },
  [FurnitureType.Stove]: {
    type: FurnitureType.Stove,
    cost: 600,
    name: 'Bếp',
    description: 'Bếp nấu ăn.',
    color: '#4a4a4a',
    styleGen: 15,
    comfortGen: 0,
  },
  [FurnitureType.Oven]: {
    type: FurnitureType.Oven,
    cost: 800,
    name: 'Lò nướng',
    description: 'Lò nướng hiện đại.',
    color: '#2f2f2f',
    styleGen: 20,
    comfortGen: 5,
  },
  [FurnitureType.Fridge]: {
    type: FurnitureType.Fridge,
    cost: 1000,
    name: 'Tủ lạnh',
    description: 'Tủ lạnh hai cánh.',
    color: '#c0c0c0',
    styleGen: 15,
    comfortGen: 10,
  },
  [FurnitureType.WashingMachine]: {
    type: FurnitureType.WashingMachine,
    cost: 700,
    name: 'Máy giặt',
    description: 'Máy giặt tự động.',
    color: '#f0f0f0',
    styleGen: 10,
    comfortGen: 20,
  },
  [FurnitureType.Speaker]: {
    type: FurnitureType.Speaker,
    cost: 300,
    name: 'Loa',
    description: 'Loa âm thanh chất lượng cao.',
    color: '#1a1a2e',
    styleGen: 15,
    comfortGen: 10,
  },
  [FurnitureType.Lamp]: {
    type: FurnitureType.Lamp,
    cost: 200,
    name: 'Đèn',
    description: 'Đèn trang trí hiện đại.',
    color: '#ffd700',
    styleGen: 20,
    comfortGen: 15,
  },
  [FurnitureType.Bathtub]: {
    type: FurnitureType.Bathtub,
    cost: 1500,
    name: 'Bồn tắm',
    description: 'Bồn tắm thư giãn.',
    color: '#e8f4f8',
    styleGen: 25,
    comfortGen: 30,
  },
};
